version: '3'
services:
  raft1:
    image: dqlite
    ports:
      - "9001:9001"
    networks:
        raft-cluster:
            ipv4_address: 172.24.2.1
    command: dqlite-benchmark --db 172.24.2.1:9001 --driver --cluster 172.24.2.1:9001,172.24.2.2:9002,172.24.2.3:9003 --workload kvreadwrite --workers 9
    volumes: 
      - ./output:/tmp/dqlite-benchmark/
  raft2:
    image: dqlite
    ports:
      - "9002:9002"
    networks:
        raft-cluster:
            ipv4_address: 172.24.2.2
    command: dqlite-benchmark --db 172.24.2.2:9002 --join 172.24.2.1:9001
    depends_on:
      - raft1
  raft3:
    image: dqlite
    ports:
      - "9003:9003"
    networks:
        raft-cluster:
            ipv4_address: 172.24.2.3 
    command: dqlite-benchmark --db 172.24.2.3:9003 --join 172.24.2.1:9001
    depends_on:
      - raft1
networks:
    raft-cluster:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "172.24.2.0/16"
